[XS2-68] 채널 내 멤버 조회 기능 Service 구현
prgrms-be-devcourse/BE-02-Slack pull request #74
Opened 2022-07-05 12:37 UTC by ecvheo1

* 채널 내 멤버 조회 기능 Service 구현입니다.

2022-07-05 12:38 UTC, ecvheo1 commented on src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
> +    if(isNotPossibleToAccessChannel(member, channelId)) {
로그인한 멤버가 조회하고 싶은 채널 내 멤버들에 접근할 수 있는지 확인하는 분기문입니다.

2022-07-05 13:06 UTC, waterfogSW approved these changes
![ExcitedHappyGIF](https://user-images.githubusercontent.com/28651727/177334655-f4972146-3d9c-417a-9ba6-afec36231155.gif)

2022-07-05 13:06 UTC, waterfogSW commented on src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
> +    if(isNotPossibleToAccessChannel(member, channelId)) {
```suggestion
    if (isNotPossibleToAccessChannel(member, channelId)) {
```
포멧팅이 적용되지 않은것같습니다

2022-07-05 13:11 UTC, dojinyou requested changes
🥇

2022-07-05 13:11 UTC, dojinyou commented on src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
> +    if(isNotPossibleToAccessChannel(member, channelId)) {
이 부분을 if문이 아니라 Assert 문으로 처리하는 게 더 통일성 있을 것 같습니다! 

`Assert.isTrue(isNotPotssibleToAccessChannel(member, channelId), CHANNEL_NOT_ACCESS.getMsg());`

2022-07-05 13:11 UTC, dojinyou commented on src/main/java/com/prgrms/be02slack/member/exception/ErrorMessage.java
> +}
기존에 에러 메세지를 Enum Type으로 따로 사용하지 않았는 데 추가하신 이유가 있을까요?

2022-07-06 00:33 UTC, ecvheo1 commented on src/main/java/com/prgrms/be02slack/member/exception/ErrorMessage.java
> +}
에러 메시지를 도메인별로 관리하자는 이야기가 나왔는데, 이전에는 까먹고 안했었습니다..

2022-07-06 00:43 UTC, dojinyou approved these changes
👍

2022-07-06 01:47 UTC, gkdud583 commented on src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
> +    Assert.isTrue(!isNotPossibleToAccessChannel(member, channelId), CHANNEL_NOT_ACCESS.getMsg());
👍👍👍

2022-07-06 01:51 UTC, gkdud583 commented on src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java
> +    @DisplayName("로그인한 멤버가 해당 채널을 구독했다면 채널 내 멤버들을 조회하고")
"채널 내 멤버들을 조회"는 ItThrowMemberResponses @DisplayName에 있으면 더 좋을 거 같아요!

2022-07-06 01:56 UTC, gkdud583 commented on src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java
> +        assertThat(foundMemberResponseList).usingRecursiveComparison().isEqualTo(memberResponseList);
👍👍👍

2022-07-06 01:56 UTC, gkdud583 approved these changes
🦸‍♂️

2022-07-06 05:12 UTC, merged